---
-   name: Install Docker SDK dependencies
    apt:
        name:
            - python3-pip
            - virtualenv
            - python3-setuptools
        state: present
        update_cache: yes

-   name: Install urllib3
    pip:
        name: urllib3
        state: latest


-   name: Install Docker SDK for Python
    pip:
        name: docker
        state: latest
