#http:
#    resource: ../src/Http/
#    type: annotation
#    prefix:
#        en: '' # don't prefix URLs for English, the default locale
#        ru: '/ru'
#        bg: '/bg'
matrix:
    resource: ../src/Matrix/Infrastructure/Controller/
    type: annotation

store:
    resource: ../src/Store/Infrastructure/Controller/
    type: annotation
    
auth:
    resource: ../src/Auth/Infrastructure/Controller/
    type: annotation

page:
    resource: ../src/Page/Infrastructure/Controller/
    type: annotation

menu:
    resource: ../src/Menu/Infrastructure/Controller/
    type: annotation
    
guarantee:
    resource: ../src/Guarantee/Infrastructure/Controller/
    type: annotation

subscriber:
    resource: ../src/Subscriber/Infrastructure/Controller/
    type: annotation