controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    prefix:
#        en: '' # don't prefix URLs for English, the default locale
#        ru: '/ru'
#        bg: '/bg'