services:
    
    App\Matrix\Domain\Repository\ProductRepositoryInterface:
        class: App\Store\Infrastructure\Repository\ProductRepository
    
    App\Matrix\Domain\Repository\SubjectRepositoryInterface:
        class: App\Matrix\Infrastructure\Repository\SubjectRepository
        
    App\Matrix\Domain\Entity\Model\ModelRepositoryInterface:
        class: App\Matrix\Infrastructure\Repository\ModelRepository