#services:
#
#    App\Matrix\Domain\Repository\Product\ProductRepositoryInterface:
#        class: App\Matrix\Infrastructure\Repository\Product\ProductRepository
#
#    App\Matrix\Domain\Repository\SubjectRepositoryInterface:
#        class: App\Matrix\Infrastructure\Repository\SubjectRepository
#
#    App\Matrix\Domain\Entity\Model\ModelRepositoryInterface:
#        class: App\Matrix\Infrastructure\Repository\ModelRepository
#
#    App\Matrix\Domain\Repository\ColorRepositoryInterface:
#        class: App\Matrix\Infrastructure\Repository\ColorRepository