doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            store_order_uuid: App\Store\Infrastructure\Doctrine\OrderIdType
            store_message_uuid: App\Store\Infrastructure\Doctrine\MessageIdType
            store_product_subscribe_uuid: App\Store\Infrastructure\Doctrine\SubscribeProductIdType
            store_promo_code_uuid: App\Store\Infrastructure\Doctrine\PromoCodeIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Domain/Entity'
                prefix: 'App\Auth\Domain\Entity'
                alias: Auth
            Store:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Store/Domain/Entity'
                prefix: 'App\Store\Domain\Entity'
                alias: Store
            Menu:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Menu/Domain/Entity'
                prefix: 'App\Menu\Domain\Entity'
                alias: Menu
            Guarantee:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Guarantee/Domain/Entity'
                prefix: 'App\Guarantee\Domain\Entity'
                alias: Guarantee
            Subscriber:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Subscriber/Domain/Entity'
                prefix: 'App\Subscriber\Domain\Entity'
                alias: Subscriber
            Page:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Page/Domain/Entity'
                prefix: 'App\Page\Domain\Entity'
                alias: Page
            Setting:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Setting/Domain/Entity'
                prefix: 'App\Setting\Domain\Entity'
                alias: Setting

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            #dbname_suffix: '_test%env(default::TEST_TOKEN)%'
            #dbname_suffix: '%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
