# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
#flysystem:
#    storages:
#        default.storage:
#            adapter: 'local'
#            options:
#                directory: '%kernel.project_dir%/public/upload'

# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'ftp'
            options:
                host: '%env(STORAGE_FTP_HOST)%'
                username: '%env(STORAGE_FTP_USERNAME)%'
                password: '%env(STORAGE_FTP_PASSWORD)%'
                root: '%env(STORAGE_FTP_ROOT)%'
                port: 21
                passive: '%env(bool:STORAGE_FTP_PASSIVE)%' # prod - true  dev - false
                ssl: false
                timeout: 30
                ignore_passive_address: ~
#        users.storage:
#            adapter: 'aws'
#            # visibility: public # Make the uploaded file publicly accessible in S3
#            options:
#                client: 'aws_client_service' # The service ID of the Aws\S3\S3Client instance
#                bucket: 'bucket_name'
#                prefix: 'optional/path/prefix'
#                streamReads: true
#        adapters:
#            public_uploads_adapter:
#                awss3v3:
#                    client: Aws\S3\S3Client
#                    bucket: '%env(AWS_S3_BUCKET_NAME)%'
        uploads.storage.aws:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: 'bucketname'
                prefix: 'prefix'