# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
#flysystem:
#    storages:
#        default.storage:
#            adapter: 'local'
#            options:
#                directory: '%kernel.project_dir%/public/upload'

# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        uploads.storage.aws:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(S3_BUCKET)%'
                prefix: 's3'