#twig:
#    default_path: '%kernel.project_dir%/templates'

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/pion/img': images
when@test:
    twig:
        strict_variables: true
